# Site wide configuration

title: "vivshaw"
description: "portfolio site"
logo: logo.png
teaser: default-python-teaser.png
locale: en_US
url: "https://vivshaw.github.io"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: "Hannah Vivian Shaw"
  web: "https://vivshaw.github.io"
  twitter: "irreduce"
  bio: "the command line is the retina of the mind's eye"
  avatar: "selfie-small.png" # 160x160 px image for author byline
  google:
    plus:
    ad-client:
    ad-slot:
  disqus-shortname: vivshaw


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
